/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_matrix_tests.check" instead.
 */

#include <check.h>

#include "s21_matrix.h"

START_TEST(s21_create_matrix_01)
{
  int res = 0;
  matrix_t A = {0};

  res = s21_create_matrix(1, 1, &A);
  ck_assert_int_eq(res, CONVERSATION_OK);
  s21_remove_matrix(&A);

}
END_TEST

START_TEST(s21_create_matrix_02)
{
  int res = 0;
  matrix_t A = {0};

  res = s21_create_matrix(2, 2, &A);
  ck_assert_int_eq(res, CONVERSATION_OK);
  s21_remove_matrix(&A);

}
END_TEST

START_TEST(s21_create_matrix_03)
{
  int res = 0;
  matrix_t A = {0};

  res = s21_create_matrix(3, 2, &A);
  ck_assert_int_eq(res, CONVERSATION_OK);
  s21_remove_matrix(&A);

}
END_TEST

START_TEST(s21_create_matrix_04)
{
  int res = 0;
  matrix_t A = {0};

  res = s21_create_matrix(2, 4, &A);
  ck_assert_int_eq(res, CONVERSATION_OK);
  s21_remove_matrix(&A);


}
END_TEST

START_TEST(s21_create_matrix_05)
{
 int res = 0;
  matrix_t A = {0};

  res = s21_create_matrix(10, 15, &A);
  ck_assert_int_eq(res, CONVERSATION_OK);
  s21_remove_matrix(&A);

}
END_TEST

START_TEST(s21_create_matrix_06)
{
  int res = 0;
  matrix_t A = {0};

  res = s21_create_matrix(0, 0, &A);
  ck_assert_int_eq(res, CONVERSATION_ERROR);

}
END_TEST

START_TEST(s21_create_matrix_07)
{
  int res = 0;
  matrix_t A = {0};

  res = s21_create_matrix(1, 0, &A);
  ck_assert_int_eq(res, CONVERSATION_ERROR);

}
END_TEST

START_TEST(s21_create_matrix_08)
{
  int res = 0;
  matrix_t A = {0};

  res = s21_create_matrix(0, 1, &A);
  ck_assert_int_eq(res, CONVERSATION_ERROR);

}
END_TEST

START_TEST(s21_create_matrix_09)
{
  int res = 0;
  matrix_t A = {0};

  res = s21_create_matrix(-1, 1, &A);
  ck_assert_int_eq(res, CONVERSATION_ERROR);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, s21_create_matrix_01);
    tcase_add_test(tc1_1, s21_create_matrix_02);
    tcase_add_test(tc1_1, s21_create_matrix_03);
    tcase_add_test(tc1_1, s21_create_matrix_04);
    tcase_add_test(tc1_1, s21_create_matrix_05);
    tcase_add_test(tc1_1, s21_create_matrix_06);
    tcase_add_test(tc1_1, s21_create_matrix_07);
    tcase_add_test(tc1_1, s21_create_matrix_08);
    tcase_add_test(tc1_1, s21_create_matrix_09);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
